// Auto-generated by make — do not edit
let buildVersion = "1.8.1"
let buildCommit = "8a67934"
let buildBranch = "main"
let buildDate = "2026-07-09 13:19:11 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
