// Auto-generated by make — do not edit
let buildVersion = "1.8.2"
let buildCommit = "f26dde9"
let buildBranch = "main"
let buildDate = "2026-07-09 14:51:10 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
