// Auto-generated by make — do not edit
let buildVersion = "1.3.7"
let buildCommit = "f8f213a"
let buildBranch = "main"
let buildDate = "2026-05-20 15:39:54 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
